<?php

namespace Lucmas\Reservations\Model;

use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Yajra\Auditable\AuditableWithDeletesTrait;
use Illuminate\Database\Eloquent\SoftDeletes;


class OrderProduct extends Model
{
    const NEW = 'NEW';
    const DELIVERED = 'DELIVERED';
    const TOPAY = 'TOPAY';
    const PAYED = 'PAYED';

    protected static function boot()
    {
        static::saving(function (OrderProduct $model) {
            if (is_null($model->created_at)) {
                $model->created_at = date("Y-m-d H:i:s");
                $model->updated_at = date("Y-m-d H:i:s");
            }
        });

        static::creating(function (OrderProduct $model) {
            if (is_null($model->created_at)) {
                $model->created_at = date("Y-m-d H:i:s");
                $model->updated_at = date("Y-m-d H:i:s");
            }
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function order()
    {
        return $this->belongsTo(app(Order::class));
    }

}
